### ISSUE TITLE
withOverrides and objects

### ISSUE THREAD

**Issue by lencioni** [ljharb/mocha-wrap#5]
I just ran into this quirk while using withOverrides. I wanted to override the value of something with an object, e.g.:

``` js
.use(withOverrides, SOMETHING[foo], { BAR: bar })
```

but I sometimes ran into errors like:

```
 TypeError: Cannot convert undefined or null to object
at hasOwnProperty (native)
at binder (node_modules/function-bind/index.js:24:27)
at eval (<anonymous>:3:37)
at node_modules/mocha-wrap/withOverrides.js:18:9
at forEachArray (node_modules/mocha-wrap/node_modules/for-each/index.js:28:22)
at forEach (node_modules/mocha-wrap/node_modules/for-each/index.js:18:9)
at Context.beforeEachWithOverrides (node_modules/mocha-wrap/withOverrides.js:15:4)
```

and

```
 TypeError: Cannot convert undefined or null to object
at node_modules/mocha-wrap/withOverrides.js:41:20
at forEachArray (node_modules/mocha-wrap/node_modules/for-each/index.js:28:22)
at forEach (node_modules/mocha-wrap/node_modules/for-each/index.js:18:9)
at Context.afterEachWithOverrides (node_modules/mocha-wrap/withOverrides.js:31:4)
```

To resolve this, I modified my code to move some things around like:

``` js
const overrides = {
  [foo]: { BAR: bar },
};
...
.use(withOverrides, SOMETHING, overrides)
```

**Comment by ljharb** [comment]
There'd be no way to override a property on an object without separating the object, and the property you want to override - that's why `Object.defineProperty` takes them separately too.

Originally I had `withOverrides` taking 3 arguments, `object`, `property`, `value` - but then it doesn't allow you to provide multiple properties.

**Comment by lencioni** [comment]
> Originally I had `withOverrides` taking 3 arguments, `object`, `property`, `value` - but then it doesn't allow you to provide multiple properties.

I think that would be clearer, which I think would be better (if it were called `withOverride`). People could just use it multiple times if they need to override multiple properties.

In the example case that would look like:

``` js
.use(withOverride, SOMETHING, foo, { BAR: bar })
```

and in tests it would look like:

``` js
wrap()
  .withOverride(SOMETHING, foo, { BAR: bar })
  .withOverride(SOMETHING, bar, { BAR: bar })
  .describe('...', () => {
```
